# Generated by Django 4.2.7 on 2023-12-10 08:35

import api.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='None', max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст сообщения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conversationparticipants')),
            ],
        ),
    ]
