# Generated by Django 4.2.7 on 2023-12-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_managers_alter_conversation_title_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationparticipants',
            unique_together={('conversation_id', 'user_id')},
        ),
    ]
