# Generated by Django 4.2.7 on 2023-12-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_conversationparticipants_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='conversationparticipants',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='conversationparticipants',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='participant_id',
            new_name='participant',
        ),
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together={('user', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipants',
            unique_together={('conversation', 'user')},
        ),
    ]
