# Generated by Django 4.2.7 on 2023-12-17 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_contact_id_contacts_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparticipants',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.conversation'),
        ),
        migrations.AlterField(
            model_name='conversationparticipants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
